# Site
name: "Bake The Lake"
title: "Bake The Lake"
description: "Teaching modern data concepts through pastry"
logo: 'assets/images/logo-text.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: ''
include: ["_pages"]
permalink: "/:title"

backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow

# Authors
authors:
  sz:
    name: SZ
    display_name: Sylvain Zyssman
    gravatar:
    email: contact@bakethelake.com
    web: https://bakethelake.com
    description: "AI Engineer - Team leader - Challenge seeker | I help companies build scalable end-to-end solutions"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-multiple-languages-plugin

# Language

languages: ["en", "fr"]
exclude_from_localizations: ["javascript", "images", "css"]
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
google_analytics: G-E848BQFP1J
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - cache/
  - gems/
  - ruby/
